### ISSUE TITLE
Missing Dependency on rv_msgs

### ISSUE THREAD

**Issue by WayTechEng** [RoboticVisionOrg/rv_panda_driver#1]
CMakeList needs to have rv_msgs as a dependency

**Comment by HanwenCao** [comment]
Hi, I hope this could help. https://github.com/RoboticVisionOrg/rv_msgs

[Edit]
The above didn't fix the issue.. Now I see. It seems that JointVelocity.h is missing.
Here is the error I got.
```
/catkin_ws/src/rv_panda_driver/include/rv_panda_driver/joint_velocity_node_controller.h:18:10: fatal error: rv_msgs/JointVelocity.h: No such file or directory
 #include "rv_msgs/JointVelocity.h"
```
Have you ever figure it out? Thank you.
