### ISSUE TITLE
Saving Named Poses error

### ISSUE THREAD

**Issue by HanwenCao** [RoboticVisionOrg/rv_panda_driver#2]
Hi, I successfully bringup the robot and call
`rosservice call /arm/set_named_pose "pose_name: 'test_pose' overwrite: false"`
But it throws an error:
```
yaml.parser.ParserError: while parsing a block mapping
  in "<string>", line 1, column 1:
    pose_name: 'test_pose' overwrite ... 
    ^
expected <block end>, but found '<scalar>'
  in "<string>", line 1, column 24:
    pose_name: 'test_pose' overwrite: false
```
Could anyone help me out! Thank you!

Btw, the error disappears if I call without overwrite: false, i.e., `rosservice call /arm/set_named_pose "pose_name: 'test_pose'"`

**Comment by suddrey-qut** [comment]
The CLI for rostopic and rosservice accept arguments in two formats YAML (the default) and JSON.

rosservice is trying to parse the following string as YAML (which is invalid due to the lack of a newline between the entry.
```sh
"pose_name: 'test_pose' overwrite: false" 
```

Try converting it to JSON using the following:
```sh
'{"pose_name": "test_pose", "overwrite": false}'
```
